// Data contract between the classification pipeline and the report UI.
// The UI never invents classifications: everything shown is derived from these fields
// plus the thresholds in ReportMethods.

/** Rank names come from the reference database's taxonomy, not from the UI. */
export type RankName = string;

export interface RankCall {
  rank: RankName;
  /** Classifier's predicted name at this rank, even if below the support cut-off. */
  name: string;
  /** Classifier confidence at this rank (e.g. bootstrap support), 0–1. */
  confidence: number;
}

export interface ReferenceHit {
  accession: string;
  taxon: string;
  /** Lineage of the reference record, index-aligned with ReportMethods.ranks. */
  lineage: string[];
  identity: number; // % identity
  coverage: number; // % query coverage
}

/** Structured reasons for stopping above species. Generated by the pipeline, not the UI. */
export type ReasonCode =
  | 'LOW_IDENTITY' // best match below the identity threshold for the next rank
  | 'SPLIT_HITS' // top hits disagree at the next rank
  | 'BELOW_CONFIDENCE' // classifier support below cut-off at the next rank
  | 'NO_DOMAIN_SUPPORT'; // nothing supported, even at the top rank

export interface Reason {
  code: ReasonCode;
  detail: string;
}

export type FlagCode = 'LIKELY_CONTAMINANT' | 'IN_NEGATIVE_CONTROL' | 'LOW_READS';

export interface Asv {
  id: string;
  sequence: string;
  reads: number;
  /** One call per rank, index-aligned with ReportMethods.ranks. */
  calls: RankCall[];
  topHits: ReferenceHit[];
  reasons: Reason[];
  flags: FlagCode[];
}

export interface QcStep {
  label: string;
  reads: number;
}

export interface ControlHit {
  control: string;
  taxon: string;
  reads: number;
}

export interface ReportMethods {
  marker: string;
  primers: string;
  referenceDb: string;
  classifier: string;
  pipelineVersion: string;
  ranks: RankName[];
  /** A rank is "supported" when confidence >= this cut-off. */
  supportCutoff: number;
  /** Confidence band lower bounds (at the deepest supported rank). */
  confidenceBands: { high: number; moderate: number };
  /** Reference divergence bands, by best-hit % identity. */
  divergenceBands: { lowMinIdentity: number; mediumMinIdentity: number };
  /** Minimum % identity typically expected for an assignment at each rank (shown in reasons). */
  identityThresholds: Record<RankName, number>;
  minReadsDefault: number;
}

export interface SampleContext {
  sampleId: string;
  project: string;
  latitude: number;
  longitude: number;
  locality: string;
  collectedAt: string; // ISO, UTC
  depthM: number;
  depthZone: string;
  environment: string;
  sampleType: string;
  volumeFiltered: string;
  filter: string;
}

export interface Report {
  isDemoData: boolean;
  generatedAt: string;
  sample: SampleContext;
  methods: ReportMethods;
  qc: QcStep[];
  controls: ControlHit[];
  asvs: Asv[];
}
